### ISSUE TITLE
Previewing Theme with PP

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/personas-plus#101]
Submitting on behalf of Pam. 

Users must apply a change in order to 'test' a customized theme they have created or uploaded using PP. After they are finished testing their new theme, it is hard to revert back to their old theme. (Pam reported having to go to AMO to find the theme she had had enabled.) 

Would it be possible to implement a 'click to preview/click to cancel preview'function for PP, similar to what is currently implemented on AMO? 

As a separate note, what is currently the easiest way to revert back to a previously enabled theme? 

.

**Comment by wagnerand** [comment]
Reverting will be very challenging until https://bugzilla.mozilla.org/show_bug.cgi?id=1369209 is fixed. I can revert to the last *installed* active theme, but due to the way Personas Plus works currently, that might not be the last *active* theme.

**Comment by VanillaOrchids** [comment]
Tonight I went to test a Theme and when I went back to the page the Theme I was using previously was on (thinking I'd have to add it back, as Caitlin described above), I noticed that just by mousing over it brought back the one I was previously using.  So it seems as if applying a custom theme offline will only stay active if you don't mouse over another theme. As soon as you do that, it reverts back. Or that's what it seems to be doing now. I didn't notice that previously when I emailed Caitlin about it.

In one way that's a good thing but not so much for someone who wants to use a Theme that would otherwise be rejected if uploaded to AMO. 

Also, for testing purposes, I applied a custom Theme from my computer and then closed Firefox and reopened it to see if it stayed put. While on initial loading it appeared that my previous Theme was going to load, it quickly switched to the custom Theme I applied before restarting Firefox. But again, mousing over a Theme on AMO changed it back.

I hope this makes sense!

Pam

**Comment by wagnerand** [comment]
Hi Pam,

if I understand you correctly, you're using the AMO website's preview feature together with PersonasPlus. Personas Plus cannot interact with the website preview, and restoring the previous theme after looking at a preview will be tricky until https://bugzilla.mozilla.org/show_bug.cgi?id=1369209 is fixed. I hope that will happen rather sooner than later!

Thank you for hanging in there!
