### ISSUE TITLE
Installing a theme from Random Selection From Featured does not add the theme to My Recently Selected

### ISSUE THREAD

**Issue by madalincm** [mozilla/personas-plus#39]
Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
Personas Plus version 1.8.0b1

### Steps to reproduce:
1. Go to tools - Personas - My Recently Selected and make a note of the listed themes.
2. Go to tools - Personas - Featured and click the Random Selection From Featured.
3. Go again to tools - Personas - My Recently Selected and observe the list.

### Expected results:
The theme installed from Random Selection From Featured is displayed in the list.

### Actual results:
The theme installed from Random Selection From Featured is not displayed in the list.

Screencast for this issue:
![personasplus01](https://cloud.githubusercontent.com/assets/15685441/16870207/136b3da6-4a89-11e6-9e5c-337b5d6df5a0.gif)

**Comment by wagnerand** [comment]
Adding @derinb.

It's not a super urgent bug, we could work on it after 1.8. If you want to fix it for 1.8, that works for me too :)

**Comment by derinb** [comment]
Guys, again this is an existing issue on [AMO version](https://addons.mozilla.org/en-US/firefox/addon/personas-plus/).

I will fix them for sure but it will be great if you prioritize Restartless related issues. That way, transition from Restart to Restartless will be more easy and painless. And it will be more easy to fix issues because it will be more easy to detect whether the issue belongs to Restart and Restartless version.

Let me fix this after 1.8.

**Comment by wagnerand** [comment]
@derinb I asked your QA team to test and find *any* issues, not only restartless related ones. And I appreciate their extensive tests because that has never been done before.

Of course, restartless bugs have a high priority, bug other bugs can be important and required for 1.8 as well.

I already stated in my comment that this can wait until after 1.8.
