### ISSUE TITLE
After pressing “Undo” button, the theme is not removed

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/personas-plus#40]
Steps to reproduce:

1.Install the Personas Plus version 1.8.0b1 add-on
2.Under the URL bar in the top right side there is an “Undo” button, press it.

Expected results:
The theme is removed.

Actual results:
The theme is not removed.

Note/Issues:
Verified on FF48.0b7(Win 7 64-bit)
This issue is reproducing in AMO production server
This issue is reproducing with e10s enabled and disabled

Here is a video:
![undo](https://cloud.githubusercontent.com/assets/15885467/16872638/bdd7844a-4a96-11e6-9d6a-8d957dfa05ea.gif)

**Comment by wagnerand** [comment]
So, a theme was already active when you installed PP, and after you did the bar showed up saying "You selected the persona..."?

**Comment by derinb** [comment]
Thanks for the report.

This should be fixed by PR #44

Please test it on a fresh profile.

@wagnerand , could you re-compile the XPI for them please.

**Comment by cosminbadescuSV** [comment]
No theme was active when I installed PP, after I installed PP only the applied theme was loaded.
After I uninstalled PP and reinstalled the applied theme was not loaded.

**Comment by derinb** [comment]
I am sorry for the confusion. I assumed this was for the Undo which is available when Removing an add-on in about:addons.

You are right about the bug. Current AMO version tries to "revertToPreviousPersona" when Undo is clicked.

But because Restartless version install a theme for the first install there is no previous theme so "revertToPreviousPersona" does not happen.

I think this is a minor bug, I will later handle this bug after fixing the other ones.

User can choose Default from toolbar button menu if she wants to Undo first install theme.

Though, Undo button works if you choose other themes from Featured list because the first theme because Previous theme now.

**Comment by wagnerand** [comment]
We could easily revert to the "default" theme in revertToPreviousPersona` if there is no actual previous persona.

It would be good to fix this for 1.8 because first time users might get confused when the "undo" button of something that suddenly changed does not work.

**Comment by derinb** [comment]
[PR 46](https://github.com/mozilla/personas-plus/pull/46) should fix this.

**Comment by cosminbadescuSV** [comment]
I tried with 1.8.0b3. here are the results:
-1.8.0b3. e10s enabled:
![undoe10senabled](https://cloud.githubusercontent.com/assets/15885467/16909555/3dafb218-4cdc-11e6-8053-5cee55c77f28.gif)


-1.8.0b3. e10s disabled:
![undoe10sdisabled](https://cloud.githubusercontent.com/assets/15885467/16909609/80b7f28c-4cdc-11e6-9ba5-092d58ac9620.gif)

**Comment by wagnerand** [comment]
Ok, according to your latest screenshots, this is working as expected. Thank you!
