### ISSUE TITLE
Disabling custom personas does not remove the custom persona displayed in browser

### ISSUE THREAD

**Issue by madalincm** [mozilla/personas-plus#43]
Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
Personas Plus version 1.8.0b1

### Steps to reproduce:
1. Go to tools - Personas - Preferences and enable custom personas
2. go to tools - Personas - Custom Persona and click the Edit button
3. Upload a header image and apply the custom persona
4. Go again to preferences and disable the custom personas

### Expected results:
The custom persona is disabled and the browser comes back to the default theme

### Actual results:
The custom persona is still displayed.

Screencast for this issue:
![custompersonasdisable](https://cloud.githubusercontent.com/assets/15685441/16874243/df50cab4-4aa0-11e6-9d37-112803324f7f.gif)

**Comment by wagnerand** [comment]
Good catch! Adding @derinb.

**Comment by derinb** [comment]
Thanks for the report.

This bug is already present in current AMO version:
https://addons.mozilla.org/en-US/firefox/addon/personas-plus/

I think this is expected behavior in some way. Because in current execution, after checking "enable custom personas", only a Custom Menu added to toolbar dropdown menu. No default Custom Theme is enabled or installed.

So when user removes check from "enable custom personas" and press OK, she should expect only to remove Custom Persona from toolbar dropdown menu. She may want to still keep her hard worked and precious Custom persona. 

If she wants to remove Custom persona after unchecking "enable custom personas", she can go to toolbar dropdown menu and choose Default or other Featured theme.

I think @madalincm is right. After clicking OK, a "confirmation box" to offer Custom persona may be offered.

But this is a minor issue. Let me fix after releasing Restart verssion of PP.

**Comment by wagnerand** [comment]
If you uncheck "Enable custom persona", one expects the custom persona to be disabled. I agree the menu label is not quite correct for the behavior.

Let's reset the persona back to default if someone disables that checkbox. While it's minor, 1.8.0 will already contain a bunch of bugfixes around custom personas, so let's include this as well and make that whole feature work nicely.

**Comment by derinb** [comment]
Andreas, the preference name is even named `extensions.personas.showCustomMenu`. 

It handles the Custom Menu. Some users may complain if they toggle `extensions.personas.showCustomMenu` from `about:config` and see the Custom theme is switched to default without warning.

I think we should keep it as it is because users are used to the way it works.

Other thing, only way to implement is to add a pref observer for `extensions.personas.showCustomMenu`. Pref observers are performance degrading and I think it does not go well with such a minor fix.

What do you think?

**Comment by derinb** [comment]
OK it seems a few lines needed to patch.

Do you accept the patch as pref observer way?

**Comment by wagnerand** [comment]
I care more about UI facing elements (like popup labels) than I do about preference names.

Pref observers are not that bad. What we could do is the following:
If the pref changes, we can show a dialog asking whether we should reset the custom persona.

Given the importance of this feature, I'd even argue for removing that checkbox altogether and just show the menu entry always.

**Comment by derinb** [comment]
OK let me do it without dialog for asking because after Pref window is closed showing a dialog may seem weird. I will automatically switch to Default theme if a Custom theme is active and the pref is disabled.

**Comment by wagnerand** [comment]
> OK let me do it without dialog for asking because after Pref window is closed showing a dialog may seem weird.

Yeah, I thought the same.

What do you think about removing the pref (and dialog entry) completely?

**Comment by derinb** [comment]
Maybe later :)

I will remove windows and switch to "tab" based options like Firefox Options page when Electrolysis lands. Till then it can stay as it is because many things will change completely.

**Comment by wagnerand** [comment]
Ok, let me remove it then. The survey we made clearly showed this is one of the most used features, so we shouldn't hide it behind a pref.

**Comment by derinb** [comment]
Or just set the pref to "true" in defaults/prefs.

**Comment by wagnerand** [comment]
Info for QA: This has been fixed by completely removing the entry in the options and thus enabling _Custom Personas_ by default.

**Comment by madalincm** [comment]
Verified as fixed in FF47(Win7) in  Personas Plus version 1.8.0b3
As stated in previous comment the Custom Personas option is now enabled by default.
