### ISSUE TITLE
The option to disable the text color is not working

### ISSUE THREAD

**Issue by madalincm** [mozilla/personas-plus#49]
Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
Persona Plus version: 1.8.0b3

### Steps to reproduce:
1. Apply a theme that has a text color other than the default one, or use a custom persona and select a custom color
2. Go to tools - Personas - Preferences and deselect Use text color and Use accent color.

### Expected results:
The theme text color becomes the default one.

### Actual results:
The original color of the theme is displayed.

### Notes/Issues:
Issue can be reproduced in FF 47.0b7

### Screencast for this issue:
![colorissue](https://cloud.githubusercontent.com/assets/15685441/16945314/21a0e692-4dad-11e6-9dcf-1a34ed11a0c8.gif)

**Comment by wagnerand** [comment]
This should be easy to fix, so let's try and do it for 1.8.0.

**Comment by derinb** [comment]
This seems complicated to me. Some themes on AMO defines textcolor in theme definition. If a black background theme is installed whose text color is white and the default Firefox theme is black, disabling text color option will make the navigation toolbox unreadable. Black textcolor over black background will be issue.

Preferences wording is not clear too. Preferences seem to affect Global but we are talking here for Custom Persona.

Any thoughts?

**Comment by wagnerand** [comment]
Yeah I agree it should affect custom personas only.

**Comment by derinb** [comment]
OK, then we should remove the options from pref.xul and adjust the customEditor.xul accordingly?

**Comment by derinb** [comment]
How do we proceed this please, @wagnerand?

**Comment by wagnerand** [comment]
Actually, I think it makes sense to have this setting effect all personas and not just custom ones.

The advantage is that a user can override the text-color of a Persona if they want/need to. If they set it to something that makes the text unreadable, it's their choice.

I think what we need is an override in the preferences, so a checkbox with a color picker, instead of just an on/off checkbox.

**Comment by derinb** [comment]
They are handled in applyPersona.
https://github.com/mozilla/personas-plus/blob/master/extension/modules/personas.js#L425
https://github.com/mozilla/personas-plus/blob/master/extension/modules/personas.js#L522

I suppose there are many backward compatibility and workaround code. Not sure, previous commits did not handle disable cases. Many it is intended?

**Comment by derinb** [comment]
Having a second look, I think we can solve disable cases by simply else clauses.

**Comment by derinb** [comment]
That applyPersona belongs to old API. Current Firefox uses `_notifyPersonaChanged` and `LightWeightThemeManager`

https://github.com/mozilla/personas-plus/blob/master/extension/modules/service.js#L719
https://github.com/mozilla/personas-plus/blob/master/extension/modules/service.js#L724

All I can do delete `accentcolor` and `textcolor` properties from `aPersona` object for disabled case before activating theme at line 724, but I think LightWeightThemeManager may complain.

@wagnerand , do you recommend property deletion?

**Comment by derinb** [comment]
Andreas, I think deleting the properties also is not solution because whole Persona JSON is saved in preferences anyway. So deleting properties before installing the Persona theme may arise issues.

So it seems those preferences belong to old API before LightWeightThemeManager and should be removed.

Your idea about overwriting colors is good but the purpose is not suitable for Personas Plus. Users can install userstyles by Stylish if they want to overwrite the colors.

I think you should change milestone to 1.8.1 because this is very complicated issue.

**Comment by derinb** [comment]
@wagnerand, will you update milestone or should I remove those 2 prefs and related options and locales?

**Comment by wagnerand** [comment]
Does any other code use the old API?

**Comment by derinb** [comment]
Those 2 prefs are observed by
https://github.com/mozilla/personas-plus/blob/master/extension/modules/service.js#L148
https://github.com/mozilla/personas-plus/blob/master/extension/modules/service.js#L149

Then [onUseColorChanged](https://github.com/mozilla/personas-plus/blob/master/extension/modules/service.js#L996) calls` Observers.notify("personas:persona:changed");` but the `"personas:persona:changed"` is not registered so it never gets called.

So I think `"personas:persona:changed"` observer is intentionally removed from add-on because it operates old api.

As is now, [L148](https://github.com/mozilla/personas-plus/blob/master/extension/modules/service.js#L148) and [L149](https://github.com/mozilla/personas-plus/blob/master/extension/modules/service.js#L148) does not seem to work. Removing both also suggest to remove those 2 prefs and related locales.

**Comment by wagnerand** [comment]
Hm, I'm not sure whether your comment answers my question. Sorry I am not that familiar with that part of the code.

**Comment by derinb** [comment]
`perWindow` pref also uses some old API code. And `perWindow` feature is also not working properly. There are some section of `perWindow` code that intersects with these 2 color prefs.

So this issue is very complicated. Please milestone it to 1.8.1 so that we can pay more caution over it when we handle it.

**Comment by wagnerand** [comment]
So, after some more digging, this feature was disabled since we implemented `LightweightThemeManager` which was around 4.0. Let's just remove all leftover code, then.

I am fine with delaying cleanup work until after 1.8.0, but we should at least remove the two prefs and the two related entries in the options dialog. That should be an easy thing to do.

**Comment by derinb** [comment]
I think we should only remove 2 prefs xul tags from preferences.xul and related locale files.

2 prefs should still be there. Because when `perWindow` is activated it looks for those 2 prefs in if conditionals.

If it is ok, I am just removing locales and prefs.xul tags?

**Comment by wagnerand** [comment]
I wonder if `perWindow` still works in recent versions? I am inclined to say we remove it as well, as it just hacks around `LightweightThemeManager` and is bound to break.

**Comment by wagnerand** [comment]
I guess it doesn't it worse to keep the prefs for 1.8.0. I just don't like having even more (dead) prefs around. Can you please file a follow up bug so we don't forget to clean up all the dead code?

**Comment by derinb** [comment]
I opened [new issue](https://github.com/mozilla/personas-plus/issues/59) for removing remnant preferences.

**Comment by derinb** [comment]
just had a quick look for `perWindow` and yes it works buggy. But there are too many code reference. Not to break things unintentionally lets remove it for the next update after 1.8.0. [Related issue](https://github.com/mozilla/personas-plus/issues/60).
