### ISSUE TITLE
Removing Personas Plus will also remove the enabled theme instead of default theme

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/personas-plus#50]
Steps to reproduce:

1.Install the Personas Plus version 1.8.0b3 add-on.
2.Install some themes from “Featured”.
3.Go to about:addons and remove Personas Plus.

Expected results:
The default theme from Personas Plus (Groovy Blue) is removed.

Actual results:
The theme applied by default by Personas plus (Groovy Blue) is not removed.

Note/Issues:
Verified on FF48.0b7(Win 7 64-bit)
This issue is reproducing in AMO production server

Here is a video:
![lasttheme](https://cloud.githubusercontent.com/assets/15885467/16948830/97e77f8e-4dbf-11e6-8af1-48adc975d1a8.gif)

**Comment by wagnerand** [comment]
I guess we need to decide what to do when PP gets uninstalled:

* If _Groovy Blue_ is the current theme, let's remove it and active the default (no) theme.
* If _Groovy Blue_ is not the current theme, let's remove it anyway. I don't think we should switch back to the default (no) theme in this case as well. The user made a decision to pick/install another theme, so PP should probably respect that and not revert that decision.

**Comment by wagnerand** [comment]
This is slightly related to #48, so setting the same milestone.

Why is it related?
If the user has a custom persona and that is not the current theme, what should PP do with it if PP is being uninstalled/disabled?

**Comment by derinb** [comment]
Is not this expected behavior? Addons suppose to revert back all changes to the state when the add-on is installed. Because at first install, there is no Personas Theme, PP removes the last active tab when uninstalled and make sure there is no remnant.

Some users just try a few themes, then do not like Personas themes, and simply go and remove the add-on. If the add-on does not remove last active theme, they may think add-on did not clean up properly and complain about it in AMO reviews.

PP also removes them when add-on is disabled because some users may want to disable add-on temporarily for another add-on that installs or previews Light Weight Theme.

**Comment by wagnerand** [comment]
It is correct that add-ons are supposed to revert changes made to the browser. However, in this case, the *user* made that change.

If the user chose another theme after installing PP, we could ask them whether they want to keep it or revert when PP is getting disabled/uninstalled.

**Comment by derinb** [comment]
OK, a confirm box could be implemented.
