### ISSUE TITLE
"Undo" drop down bar is not displayed if "Random selection from Featured" theme is added

### ISSUE THREAD

**Issue by vcarciu** [mozilla/personas-plus#53]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0
FF : 48.0b7

Steps to reproduce:
1.Install latest Personas Plus from https://addons.mozilla.org/en-US/firefox/addon/personas-plus/#beta-channel
2.From Personas Plus drop down menu , select "Featured"- "Random selection from Featured" theme

Expected results:
An "Undo" drop down bar is displayed after applying each theme

Actual results:
"Undo" drop down bar is not displayed if "Random selection from Featured" theme is added

Please see video for this bug : 
![undopp](https://cloud.githubusercontent.com/assets/1583842/16951877/883f5970-4dcf-11e6-893a-5ca1a8e28c3a.gif)

**Comment by derinb** [comment]
I think this is not good idea. Some Rotator add-ons rotate personas themes by interval say at 5 minutes interval.

If each time notification panel is shown when a new Personas theme switched, this will bother Rotator users because they will have to close it again and again unnecessarily.

If they want to Undo, they can use My Recently Selected menu.

**Comment by wagnerand** [comment]
Other add-ons don't need to show the undo bar, especially when rotating.

But PP should be consistent. We should either show the "undo bar" always or not at all.
