### ISSUE TITLE
Users can use any dimensions and file types for header and footer when creating Cusom Personas

### ISSUE THREAD

**Issue by vcarciu** [mozilla/personas-plus#54]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0
FF : 48.0b7

Steps to reproduce:
1.Install latest Personas Plus from https://addons.mozilla.org/en-US/firefox/addon/personas-plus/#beta-channel
2.From Personas Plus drop down menu , select "Custom Persona"- "Edit" 
3.Add different dimensions and file types for header and footer 

Expected results:
User is warned that only specific dimensions and file types are supported

Actual results:
No warnings displayed for wrong file types and also , no specific dimensions are enforced and this will lead to ugly personas

Please see video for this bug :   http://screencast.com/t/vatShGOdbnp0

We should use something like this when creating Custom Personas :  
![dimensions](https://cloud.githubusercontent.com/assets/1583842/16954123/4f5012ae-4dd8-11e6-8522-c38bb959966b.png)

**Comment by derinb** [comment]
We can filter selectable image types by nsIFilePicker options.

I think size should not be restricted. Even if the images are small, transparent PNG files may blend well with the background color.

Otherwise we have to expect all users to open up Image Editor software to get their hands dirty with software. 

Proposed design without forced restrictions is a great idea.

**Comment by wagnerand** [comment]
The dimensions are requirements (https://developer.mozilla.org/en-US/Add-ons/Themes/Background) so it's ok to enforce them. If other dimensions work as well, that might just be coincidence and is not supported.

Enforcing this is still better than users (or future Firefox versions) breaking the theme.
