### ISSUE TITLE
Groovy Blue theme is not removed on uninstall

### ISSUE THREAD

**Issue by wagnerand** [mozilla/personas-plus#73]
The _Groovy Blue_ theme is not removed on uninstall if another theme is active. It only gets disabled.

@derinb I trust you test all your patches before you open pull requests. I don't have time to make sure they work and we can't ask our QA team to test every new release.

**Comment by derinb** [comment]
Well I test the patches but during PR we had edits and I assumed `forgetUsedTheme` makes sure the theme is removed. Probably because previous PP version removed theme by setting `currentTheme` to null.

I am not sure actually how to remove the theme?

https://developer.mozilla.org/en-US/Add-ons/Themes/Lightweight_themes#Distributing_lightweight_themes_as_downloadable_plugins_(aka_XPIs)

Do you have any idea?

**Comment by derinb** [comment]
OK let me do it Add-on Manager way.

**Comment by wagnerand** [comment]
Hold off a minute...

**Comment by derinb** [comment]
```
		Components.utils.import("resource://gre/modules/AddonManager.jsm");  
		AddonManager.getAddonByID("15131@personas.mozilla.org", function(addon) {  
                   if(addon) addon.uninstall(true);
		});
```

I could fix it by this code.
